"""Inital migration.

Revision ID: 323bfe3fd984
Revises: 42c06214b6f6
Create Date: 2023-06-26 11:41:56.608405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323bfe3fd984'
down_revision = '42c06214b6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('labid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('questions', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('lab_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('labid'),
    sa.UniqueConstraint('lab_num'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labs')
    # ### end Alembic commands ###
