"""empty message

Revision ID: 311e2146481d
Revises: 1b44b982be14
Create Date: 2023-07-12 10:28:40.858273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311e2146481d'
down_revision = '1b44b982be14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.alter_column('questions',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('num_questions',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.alter_column('num_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('questions',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
