"""Initial migration

Revision ID: 71edb7941171
Revises: a93c6a7ebf29
Create Date: 2023-07-06 15:31:19.041388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71edb7941171'
down_revision = 'a93c6a7ebf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_course')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('section_num', sa.Integer(), nullable=True))
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('section_num')
        batch_op.drop_column('semester')

    op.create_table('_alembic_tmp_course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_instructor', sa.INTEGER(), nullable=True),
    sa.Column('semester', sa.VARCHAR(), nullable=False),
    sa.Column('section_num', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_instructor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
