"""Added new values to Group model

Revision ID: 8900a3cf5ef1
Revises: 71edb7941171
Create Date: 2023-07-10 14:01:04.493698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8900a3cf5ef1'
down_revision = '71edb7941171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('section_num', sa.Integer(), nullable=True))
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hand_raised', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('at_checkpoint', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_progress', sa.Integer(), nullable=True))

    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_questions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('num_questions')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('max_progress')
        batch_op.drop_column('progress')
        batch_op.drop_column('at_checkpoint')
        batch_op.drop_column('hand_raised')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('section_num')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
